spring.application.name=PrepAce
spring.datasource.url=jdbc:mysql://localhost:3306/prepace
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true